steps:
# This step runs the unit tests on the app
- name: 'python:3-alpine'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  - 'pip install flask && python simple_test.py -v'

# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/devops-demo:$SHORT_SHA'
  - '.'

# This step pushes the image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/devops-demo:$SHORT_SHA'
